### ISSUE TITLE
conda install -c nsls2forge databroker failed on ubuntu 22.04

### ISSUE THREAD

**Issue by LeeYangLBLBCS** [bluesky/databroker#776]
````
<!--- Provide a general summary of the issue in the Title above -->

## Expected Behavior
installation succeeds.

## Current Behavior
<!--- If describing a bug, tell us what happens instead of the expected behavior -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->

conda install -c nsls2forge databroker

Collecting package metadata (current_repodata.json): - 
\ 
/ 
failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/lyang/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 187, in conda_http_errors
        yield
      File "/home/lyang/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 153, in repodata
        response.raise_for_status()
      File "/home/lyang/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/nsls2forge/linux-64/current_repodata.json
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/lyang/miniconda3/lib/python3.10/site-packages/requests/models.py", line 971, in json
        return complexjson.loads(self.text, **kwargs)
      File "/home/lyang/miniconda3/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
        return _default_decoder.decode(s)
      File "/home/lyang/miniconda3/lib/python3.10/site-packages/simplejson/decoder.py", line 370, in decode
        obj, end = self.raw_decode(s)
      File "/home/lyang/miniconda3/lib/python3.10/site-packages/simplejson/decoder.py", line 400, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)



## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->

```[tasklist]
### Tasks
```

**Comment by tacaswell** [comment]
It should be `conda install -c conda-forge databroker`, closing as I just merged #778.

Sorry for the outdated text @LeeYangLBLBCS
